/*
 * Copyright 2015 Max Nilsson
 * Each line should be prefixed with  * 
 */
package SonarCom.Dialogs;

import SonarCom.SensorData;
import static java.awt.EventQueue.isDispatchThread;
import java.util.List;
import java.util.concurrent.BlockingQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.isEventDispatchThread;
import javax.swing.SwingWorker;

/**
 *
 * @author max
 */
public class SensorJDialog extends javax.swing.JDialog {

    private final BlockingQueue<SensorData> sensorFifo;
    private final UpdateSensorTask          updateSensorTask;

    /**
     * Creates new form SensorJDialog
     */
    public SensorJDialog(BlockingQueue<SensorData> sensorFifo) {
        super();
        this.sensorFifo = sensorFifo;
        // Initialize Swing stuff in the Event Dispatch Thread
        SwingUtilities.invokeLater(() -> {
            if (!isDispatchThread()) System.out.println("WARNING SensorJDialog.initComponents not in DT");
            initComponents();
            setVisible(true);
        });
        
        this.updateSensorTask = new UpdateSensorTask();
        this.updateSensorTask.execute();
        System.out.println("Started UpdateSensorTask");
    }

    
    /* Task that updates jDialog with SensorData data */
    private class UpdateSensorTask extends SwingWorker<Void, SensorData> {
        @Override
        protected Void doInBackground() throws InterruptedException {
            SensorData sensorData;
            if (isDispatchThread()) System.out.println("WARNING SensorJDialog.doInBackground in DT");

            // Don't continue until Dialog is initiated and visible
            while(!isVisible()) {
//                System.out.println("UpdateSensorTask, SensorJDialog not yet visible");
                Thread.sleep(50);
            }

            while (true) {
                sensorData = sensorFifo.take();
                publish(sensorData);
            }
        }
        
        @Override
        protected void process(List<SensorData> sensorDataList) {
            if (!isDispatchThread()) System.out.println("WARNING SensorJDialog.process not in DT");
            for (SensorData sensorData : sensorDataList) {
                if (sensorData.depthValid) {
                    jLabelDepth.setText(sensorData.depth());
                }  
                if (sensorData.headingValid) {
                    jLabelHeading.setText(sensorData.heading());
                }  
                if (sensorData.pitchValid) {
                    jLabelPitch.setText(sensorData.pitch());
                }  
                if (sensorData.rollValid) {
                    jLabelRoll.setText(sensorData.roll());
                }  
                if (sensorData.temperatureValid) {
                    jLabelSensBoardTemp.setText(sensorData.sensorBoardTemp());
                    jLabelSensIrTemp.setText(sensorData.irTemp());
                }  
                if (sensorData.voltageValid) {
                    jLabelVoltage.setText(sensorData.voltage());
                }  
                if (sensorData.currentValid) {
                    jLabelCurrent.setText(sensorData.current());
                }  
            }
        }
        
        @Override
        public void done() {
            System.out.println("UpdateSensorTask done(?)");
        }

    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelDepth = new javax.swing.JLabel();
        jLabelHeading = new javax.swing.JLabel();
        jLabelPitch = new javax.swing.JLabel();
        jLabelRoll = new javax.swing.JLabel();
        jLabelSensBoardTemp = new javax.swing.JLabel();
        jLabelSensIrTemp = new javax.swing.JLabel();
        jLabelVoltage = new javax.swing.JLabel();
        jLabelCurrent = new javax.swing.JLabel();

        setTitle("SonarCom");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SonarFish"));

        jLabelDepth.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelDepth.setText("-");
        jLabelDepth.setToolTipText("SonarFish depth");
        jLabelDepth.setBorder(javax.swing.BorderFactory.createTitledBorder("Depth"));
        jLabelDepth.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelDepth.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelDepth.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelHeading.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelHeading.setText("-");
        jLabelHeading.setToolTipText("SonarFish compas heading");
        jLabelHeading.setBorder(javax.swing.BorderFactory.createTitledBorder("Heading"));
        jLabelHeading.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelHeading.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelHeading.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelPitch.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelPitch.setText("-");
        jLabelPitch.setBorder(javax.swing.BorderFactory.createTitledBorder("Pitch"));
        jLabelPitch.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelPitch.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelPitch.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelRoll.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelRoll.setText("-");
        jLabelRoll.setBorder(javax.swing.BorderFactory.createTitledBorder("Roll"));
        jLabelRoll.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelRoll.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelRoll.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelSensBoardTemp.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelSensBoardTemp.setText("-");
        jLabelSensBoardTemp.setBorder(javax.swing.BorderFactory.createTitledBorder("Sens T"));
        jLabelSensBoardTemp.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelSensBoardTemp.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelSensBoardTemp.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelSensIrTemp.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelSensIrTemp.setText("-");
        jLabelSensIrTemp.setBorder(javax.swing.BorderFactory.createTitledBorder("IR temp"));
        jLabelSensIrTemp.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelSensIrTemp.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelSensIrTemp.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelVoltage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelVoltage.setText("-");
        jLabelVoltage.setBorder(javax.swing.BorderFactory.createTitledBorder("Voltage"));
        jLabelVoltage.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelVoltage.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelVoltage.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelCurrent.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelCurrent.setText("-");
        jLabelCurrent.setBorder(javax.swing.BorderFactory.createTitledBorder("Current"));
        jLabelCurrent.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelCurrent.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelCurrent.setPreferredSize(new java.awt.Dimension(70, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSensBoardTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDepth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelSensIrTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSensBoardTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSensIrTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCurrent;
    private javax.swing.JLabel jLabelDepth;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelPitch;
    private javax.swing.JLabel jLabelRoll;
    private javax.swing.JLabel jLabelSensBoardTemp;
    private javax.swing.JLabel jLabelSensIrTemp;
    private javax.swing.JLabel jLabelVoltage;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
