/*
 * Copyright 2015 Max Nilsson
 * Each line should be prefixed with  * 
 */
package SonarCom.Dialogs;

import SonarCom.GpsData;
import static java.awt.EventQueue.isDispatchThread;
import java.util.List;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author max
 */
public class GpsJDialog extends javax.swing.JDialog {

    private final BlockingQueue<GpsData> gpsFifo;
    private final UpdateGpsTask          updateGpsTask;

    /**
     * Creates new form SensorJDialog
     */
    public GpsJDialog(BlockingQueue<GpsData> gpsFifo) throws InterruptedException {
        super();
        this.gpsFifo = gpsFifo;
       // Initialize Swing stuff in the Event Dispatch Thread
        SwingUtilities.invokeLater(() -> {
            if (!isDispatchThread()) System.out.println("WARNING GpsJDialog.initComponents not in DT");
            initComponents();
            setVisible(true);
        });
        
        updateGpsTask = new UpdateGpsTask();
        updateGpsTask.execute();
        System.out.println("Started UpdateGpsTask");
    }
    
    /* Task that updates jDialog with GpsData data */
    private class UpdateGpsTask extends SwingWorker<Void, GpsData> {
        @Override
        protected Void doInBackground() throws InterruptedException {
            GpsData gpsData;
            if (isDispatchThread()) System.out.println("WARNING GpsJDialog.doInBackground in DT");
            
            // Don't continue until Dialog is initiated and visible
            while(!isVisible()) {
//                System.out.println("UpdateGpsTask, GpsJDialog not yet visible");
                Thread.sleep(50);
            }

            while (true) {
                gpsData = gpsFifo.poll(2, TimeUnit.SECONDS);
                publish(gpsData);
            }
        }
        
        @Override
        protected void process(List<GpsData> gpsDataList) {
            if (!isDispatchThread()) System.out.println("WARNING GpsJDialog.process not in DT");
            for (GpsData gpsData : gpsDataList) {
                if (gpsData != null) {
                    if (gpsData.courseValid) {
                        jLabelCourse.setText(gpsData.course());
                    }  
                    if (gpsData.hdopValid) {
                        jLabelHdop.setText(gpsData.hdop());
                    }  
                    if (gpsData.latitudeValid) {
                        jLabelLatitude.setText(gpsData.latitude());
                    }  
                    if (gpsData.longitudeValid) {
                        jLabelLongitude.setText(gpsData.longitude());
                    }  
                    if (gpsData.speedValid) {
                        jLabelSpeed.setText(gpsData.speed());
                    }  
                    if (gpsData.nrSatValid) {
                        jLabelNrSatellites.setText(gpsData.nrSat());
                    }  
                    if (gpsData.fixValid) {
                        jLabelFix.setText(gpsData.fixQuality());
                    }  
                    if (gpsData.modeValid) {
                        jLabelMode.setText(gpsData.mode());
                    }  
                } else {
                    jLabelCourse.setText("-");
                    jLabelHdop.setText("-");
                    jLabelLatitude.setText("-");
                    jLabelLongitude.setText("-");
                    jLabelSpeed.setText("-");
                    jLabelNrSatellites.setText("0");
                    jLabelFix.setText("None");
                    jLabelMode.setText("-");
                }
            }
        }
        
        @Override
        public void done() {
            System.out.println("UpdateGpsTask done(?)");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLongitude = new javax.swing.JLabel();
        jLabelLatitude = new javax.swing.JLabel();
        jLabelSpeed = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();
        jLabelNrSatellites = new javax.swing.JLabel();
        jLabelHdop = new javax.swing.JLabel();
        jLabelFix = new javax.swing.JLabel();
        jLabelMode = new javax.swing.JLabel();

        setTitle("SonarCom");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("GPS"));

        jLabelLongitude.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelLongitude.setText("-");
        jLabelLongitude.setBorder(javax.swing.BorderFactory.createTitledBorder("Longitude"));

        jLabelLatitude.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelLatitude.setText("-");
        jLabelLatitude.setBorder(javax.swing.BorderFactory.createTitledBorder("Latitude"));

        jLabelSpeed.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelSpeed.setText("-");
        jLabelSpeed.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));
        jLabelSpeed.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelSpeed.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelSpeed.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelCourse.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelCourse.setText("-");
        jLabelCourse.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));
        jLabelCourse.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelCourse.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelCourse.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelNrSatellites.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelNrSatellites.setText("-");
        jLabelNrSatellites.setBorder(javax.swing.BorderFactory.createTitledBorder("Nr Sat."));
        jLabelNrSatellites.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelNrSatellites.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelNrSatellites.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelHdop.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelHdop.setText("-");
        jLabelHdop.setBorder(javax.swing.BorderFactory.createTitledBorder("HDOP"));
        jLabelHdop.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelHdop.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelHdop.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelFix.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelFix.setText("-");
        jLabelFix.setBorder(javax.swing.BorderFactory.createTitledBorder("Fix"));
        jLabelFix.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelFix.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelFix.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabelMode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelMode.setText("-");
        jLabelMode.setBorder(javax.swing.BorderFactory.createTitledBorder("Mode"));
        jLabelMode.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabelMode.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabelMode.setPreferredSize(new java.awt.Dimension(70, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLatitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHdop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNrSatellites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLatitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLongitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNrSatellites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHdop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelFix;
    private javax.swing.JLabel jLabelHdop;
    private javax.swing.JLabel jLabelLatitude;
    private javax.swing.JLabel jLabelLongitude;
    private javax.swing.JLabel jLabelMode;
    private javax.swing.JLabel jLabelNrSatellites;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
